using System;
using System.Reflection;
using System.Runtime.InteropServices;

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.832
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: ComVisible(false)]
[assembly: CLSCompliant(false)]
[assembly:
    AssemblyConfiguration(
        "https://axiomengine.svn.sourceforge.net/svnroot/axiomengine, Mixed Revisions, Local Modifications, Debug")]
[assembly: AssemblyCompanyAttribute("Axiom Rendering Engine Project Team (http://axiom3d.net)")]
[assembly: AssemblyProductAttribute("Axiom Rendering Engine")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2003-2012 Axiom Rendering Engine Project Team.")]
[assembly: AssemblyTrademarkAttribute("")]
[assembly: AssemblyCultureAttribute("")]

// Version information for an assembly consists of the following four values:
//
//      Major Version
//      Minor Version 
//      Build Number
//      Revision
//

[assembly: AssemblyVersion( /*  Major.Minor.Build */ "0.9.0.0")]
#if !( XBOX || XBOX360 )

[assembly: AssemblyFileVersion( /*  Major.Minor.Build */ "0.9.0.0")]
#endif

[assembly: AssemblyInformationalVersion( /*  Major.Minor.Build */ "0.9.0.0")]